"""ultracompress.bench - inference throughput benchmark for v3 packed models.

Sales-grade benchmark that customers run locally on a packed `.uc` directory
shipped to them. Measures TTFT (time-to-first-token), TPS (tokens/sec
overall), TPS decode-only, and peak VRAM. Optionally compares against the
bf16 baseline of the same HF model loaded with the standard
`AutoModelForCausalLM.from_pretrained` path.

The packed model is reconstructed from `layer_*.uc` files via
`ultracompress.load_uc.reconstruct_layer_state_dict`, then injected into a
fresh HF skeleton. This mirrors the production reload path used by
`scripts/overlay/eval_compressed_only.py`, so reported throughput reflects
exactly what customers see in production inference.

Public API:
    from ultracompress.bench import bench_packed
    result = bench_packed(packed_dir="my_model.uc", n_prompts=50, ...)

CLI entry point:
    uc bench <packed_dir> [--n-prompts N] [--seq-len N] [--n-new-tokens N]
                          [--device cuda:0] [--baseline] [--out-json PATH]
"""
from __future__ import annotations

import argparse
import datetime
import gc
import json
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

DEFAULT_PROMPTS_POOL: tuple[str, ...] = (
    "Explain the concept of model compression for large language models in a way that "
    "a non-technical executive could understand, with one concrete example.",
    "Describe the difference between supervised, unsupervised, and reinforcement learning, "
    "with one real-world application of each.",
    "Walk through how an HTTP request travels from a browser to a backend server and "
    "back, including DNS, TCP, and TLS handshakes.",
    "Summarize the key trade-offs between quantization, pruning, and knowledge "
    "distillation as model compression techniques.",
    "Outline a robust strategy for backing up a production database, including "
    "incremental snapshots, point-in-time recovery, and offsite replication.",
    "Compare the architectural differences between transformer-based and state-space "
    "models for sequence modeling, and the latency implications of each.",
    "Explain how a lossless compression scheme like Huffman coding works, contrasting "
    "it with lossy schemes such as JPEG.",
    "Describe how vector databases enable retrieval-augmented generation pipelines and "
    "the role of approximate nearest-neighbor search.",
)


@dataclass
class BenchResult:
    """Structured benchmark report. Serialized to JSON for distribution."""

    model_id: str
    n_prompts: int
    seq_len: int
    n_new_tokens: int
    device: str
    cuda_device_name: str
    ttft_s_mean: float
    tps_overall: float
    tps_decode_only: float
    peak_vram_gb: float
    timestamp: str
    baseline_tps_overall: float | None = None
    baseline_tps_decode_only: float | None = None
    baseline_ttft_s_mean: float | None = None
    baseline_peak_vram_gb: float | None = None
    comparison: dict[str, float] = field(default_factory=dict)
    warnings: list[str] = field(default_factory=list)


def _resolve_base_model_id(packed_dir: Path) -> str:
    """Read the base HF model id from the packed dir's README.md frontmatter.

    The packed dir's `README.md` is generated by the v3 upload script and has a
    YAML frontmatter block including `base_model: <hf-id>`. Falls back to a
    `manifest.json` `base_model_hf_id` key if present.
    """
    manifest_path = packed_dir / "manifest.json"
    if manifest_path.exists():
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            manifest = {}
        for key in ("base_model_hf_id", "base_model", "hf_id"):
            val = manifest.get(key)
            if isinstance(val, str) and val.strip():
                return val.strip()

    readme_path = packed_dir / "README.md"
    if readme_path.exists():
        text = readme_path.read_text(encoding="utf-8")
        for line in text.splitlines():
            line = line.strip()
            if line.startswith("base_model:"):
                return line.split(":", 1)[1].strip()
            if line.startswith("base_model_hf_id:"):
                return line.split(":", 1)[1].strip()

    raise ValueError(
        f"Could not resolve base HF model id from {packed_dir}. "
        f"Pass --base-model explicitly, or ensure manifest.json has "
        f"`base_model_hf_id` or README.md has `base_model:` frontmatter."
    )


def _free_memory() -> None:
    """Aggressive cleanup between baseline and student runs."""
    import torch

    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()


def _build_prompt(seq_len: int, tokenizer: Any, idx: int) -> str:
    """Build a prompt of approx `seq_len` tokens by repeating the pool entry."""
    base = DEFAULT_PROMPTS_POOL[idx % len(DEFAULT_PROMPTS_POOL)]
    # Repeat the base prompt until we have enough tokens, then truncate.
    text = base
    while len(tokenizer(text, return_tensors="pt").input_ids[0]) < seq_len:
        text = text + " " + base
    ids = tokenizer(text, return_tensors="pt").input_ids[0][:seq_len]
    return tokenizer.decode(ids, skip_special_tokens=True)


def _run_generation(
    model: Any,
    tokenizer: Any,
    prompts: list[str],
    n_new_tokens: int,
    device: str,
) -> dict[str, float]:
    """Run greedy generate over all prompts; return aggregate timing stats."""
    import torch

    pad_id = tokenizer.eos_token_id or 0
    use_cuda = device.startswith("cuda")
    torch_device = torch.device(device)

    # Warmup pass on first prompt to prime kernels / kv cache allocators.
    warm_inputs = tokenizer(prompts[0], return_tensors="pt").to(torch_device)
    with torch.no_grad():
        _ = model.generate(
            **warm_inputs, max_new_tokens=4, do_sample=False, pad_token_id=pad_id
        )
    if use_cuda:
        torch.cuda.synchronize(torch_device)
        torch.cuda.reset_peak_memory_stats(torch_device)

    ttft_samples: list[float] = []
    full_dt_samples: list[float] = []
    n_new_per_prompt: list[int] = []

    for prompt in prompts:
        inputs = tokenizer(prompt, return_tensors="pt").to(torch_device)
        n_prompt = inputs.input_ids.shape[1]

        # TTFT: time for prefill + 1 decode step.
        if use_cuda:
            torch.cuda.synchronize(torch_device)
        t0 = time.perf_counter()
        with torch.no_grad():
            _ = model.generate(
                **inputs, max_new_tokens=1, do_sample=False, pad_token_id=pad_id
            )
        if use_cuda:
            torch.cuda.synchronize(torch_device)
        ttft_samples.append(time.perf_counter() - t0)

        # Full generation.
        if use_cuda:
            torch.cuda.synchronize(torch_device)
        t0 = time.perf_counter()
        with torch.no_grad():
            out_full = model.generate(
                **inputs, max_new_tokens=n_new_tokens, do_sample=False,
                pad_token_id=pad_id,
            )
        if use_cuda:
            torch.cuda.synchronize(torch_device)
        full_dt_samples.append(time.perf_counter() - t0)
        n_new_per_prompt.append(int(out_full.shape[1] - n_prompt))

    ttft_mean = sum(ttft_samples) / len(ttft_samples)
    full_dt_mean = sum(full_dt_samples) / len(full_dt_samples)
    n_new_mean = sum(n_new_per_prompt) / len(n_new_per_prompt)
    decode_dt_mean = max(full_dt_mean - ttft_mean, 1e-6)

    peak_vram_gb = (
        torch.cuda.max_memory_allocated(torch_device) / (1024 ** 3)
        if use_cuda
        else 0.0
    )

    return {
        "ttft_s_mean": ttft_mean,
        "tps_overall": n_new_mean / full_dt_mean,
        "tps_decode_only": (n_new_mean - 1) / decode_dt_mean,
        "peak_vram_gb": peak_vram_gb,
    }


def _load_packed_model(
    packed_dir: Path, base_hf_id: str, device: str
) -> tuple[Any, Any]:
    """Load packed v3 model + tokenizer.

    Approach: load fresh HF skeleton in bf16, then for each `layer_NNN.uc`,
    reconstruct the per-layer state dict and replace target Linears with
    `CorrectionMatrixC` modules. Returns (model, tokenizer).
    """
    import torch
    from transformers import AutoConfig, AutoModelForCausalLM, AutoTokenizer

    from ultracompress.load_uc import reconstruct_layer_state_dict

    # CorrectionMatrixC lives in the streaming runner (research overlay). We
    # import lazily so the package stays importable without it.
    try:
        import sys as _sys

        overlay_dir = Path(__file__).resolve().parents[1] / "scripts" / "overlay"
        if overlay_dir.exists() and str(overlay_dir) not in _sys.path:
            _sys.path.insert(0, str(overlay_dir))
        from streaming_compression_runner import CorrectionMatrixC  # type: ignore
    except ImportError as exc:
        raise ImportError(
            "uc bench requires CorrectionMatrixC from "
            "scripts/overlay/streaming_compression_runner.py. "
            f"Original import error: {exc}"
        ) from exc

    torch_device = torch.device(device)
    tokenizer = AutoTokenizer.from_pretrained(base_hf_id, trust_remote_code=True)

    # v3.5 self-contained path: if the pack has aux_weights.uc, build the model
    # from CONFIG ONLY (no HF safetensors download), then inject aux tensors.
    # Falls back to the original load-from-HF behaviour for legacy v3.0 packs.
    aux_path = packed_dir / "aux_weights.uc"
    manifest_path = packed_dir / "manifest.json"
    use_aux = aux_path.exists()
    if use_aux and manifest_path.exists():
        try:
            mfst = json.loads(manifest_path.read_text(encoding="utf-8"))
            use_aux = bool(mfst.get("aux_file")) and aux_path.exists()
        except json.JSONDecodeError:
            use_aux = False

    if use_aux:
        from ultracompress.aux_pack import load_aux_into_model, parse_aux_weights

        config = AutoConfig.from_pretrained(base_hf_id, trust_remote_code=True)
        # Skeleton-only construction — no weights pulled from HF.
        model = AutoModelForCausalLM.from_config(
            config, torch_dtype=torch.bfloat16, trust_remote_code=True
        ).to(torch_device).train(False)
        aux_tensors = parse_aux_weights(aux_path)
        n_aux = load_aux_into_model(model, aux_tensors)
        print(f"[uc bench] self-contained pack: loaded {n_aux} model-level "
              f"tensors from {aux_path.name} (no HF download for aux)", flush=True)
    else:
        model = AutoModelForCausalLM.from_pretrained(
            base_hf_id, torch_dtype=torch.bfloat16, device_map=torch_device,
            trust_remote_code=True,
        ).train(False)

    layer_files = sorted(packed_dir.glob("layer_*.uc"))
    if not layer_files:
        raise FileNotFoundError(f"No layer_*.uc files in {packed_dir}")

    layers = model.model.layers
    n_layers = min(len(layer_files), len(layers))
    for i in range(n_layers):
        uc_path = packed_dir / f"layer_{i:03d}.uc"
        if not uc_path.exists():
            continue
        sd = reconstruct_layer_state_dict(uc_path)
        # Pull out correction (V/U/alpha) keys per Linear and rewrap them.
        corrections: dict[str, dict[str, torch.Tensor]] = {}
        plain: dict[str, torch.Tensor] = {}
        for k, v in sd.items():
            if k.endswith(".V.weight") or k.endswith(".U.weight") or k.endswith(".alpha"):
                base = k.rsplit(".", 2)[0] if ".weight" in k else k.rsplit(".", 1)[0]
                corrections.setdefault(base, {})[k.split(".")[-1] if k.endswith(".alpha") else k.split(".")[-2]] = v
            elif k.endswith(".W_base"):
                base = k.rsplit(".", 1)[0]
                corrections.setdefault(base, {})["W_base"] = v
            elif k.endswith(".bias") and any(
                k.startswith(b + ".") for b in corrections.keys()
            ):
                base = k.rsplit(".", 1)[0]
                corrections.setdefault(base, {})["bias"] = v
            else:
                plain[k] = v

        for lin_name, parts in corrections.items():
            if "W_base" not in parts:
                continue
            rank = parts["V"].shape[0] if "V" in parts else 32
            attrs = lin_name.split(".")
            parent = layers[i]
            for p in attrs[:-1]:
                parent = getattr(parent, p)
            attr = attrs[-1]
            existing = getattr(parent, attr)
            cm = CorrectionMatrixC(
                parts["W_base"].to(device=torch_device, dtype=torch.bfloat16),
                parts.get("bias", existing.bias.data if existing.bias is not None else None),
                rank=rank,
            )
            cm.V.weight.data.copy_(parts["V"].to(device=torch_device))
            cm.U.weight.data.copy_(parts["U"].to(device=torch_device))
            cm.alpha.data.copy_(parts["alpha"].to(device=torch_device))
            setattr(parent, attr, cm)

        if plain:
            layers[i].load_state_dict(plain, strict=False)
        layers[i] = layers[i].to(device=torch_device, dtype=torch.bfloat16)

    return model, tokenizer


def bench_packed(
    packed_dir: str | Path,
    *,
    n_prompts: int = 50,
    seq_len: int = 1024,
    n_new_tokens: int = 256,
    device: str = "cuda:0",
    baseline: bool = False,
    base_model_hf_id: str | None = None,
    out_json: str | Path | None = None,
) -> BenchResult:
    """Benchmark inference throughput on a UC v3 packed model.

    Args:
        packed_dir: Path to a UC v3 packed directory (contains layer_*.uc + manifest.json).
        n_prompts: Number of prompts to evaluate (default 50).
        seq_len: Approximate prompt length in tokens (default 1024).
        n_new_tokens: Tokens to generate per prompt with greedy decoding (default 256).
        device: Torch device string (default "cuda:0").
        baseline: If True, also load the bf16 baseline and compute speedup ratios.
        base_model_hf_id: Override for the base HF model id. If None, resolved
            from the packed dir's manifest.json or README.md frontmatter.
        out_json: If set, write the JSON-serialized result to this path. Defaults
            to `./bench_<timestamp>.json`.

    Returns:
        BenchResult dataclass with all measured metrics. Also writes JSON.

    Notes:
        Catches CUDA OOM and returns a partial result (baseline_* fields may be
        None) with the exception message captured in `warnings`. Greedy decoding
        only - reported throughput is apples-to-apples vs the bf16 baseline.
    """
    import torch

    packed_dir = Path(packed_dir).expanduser().resolve()
    if not packed_dir.is_dir():
        raise FileNotFoundError(f"Packed dir does not exist: {packed_dir}")

    base_id = base_model_hf_id or _resolve_base_model_id(packed_dir)
    use_cuda = device.startswith("cuda") and torch.cuda.is_available()
    cuda_name = (
        torch.cuda.get_device_name(torch.device(device)) if use_cuda else "cpu"
    )
    timestamp = datetime.datetime.now().isoformat(timespec="seconds")

    if out_json is None:
        ts_compact = timestamp.replace(":", "").replace("-", "")
        out_json = Path(f"./bench_{ts_compact}.json")
    out_json = Path(out_json).expanduser().resolve()
    out_json.parent.mkdir(parents=True, exist_ok=True)

    warnings_list: list[str] = []

    # Build prompts using the packed model's tokenizer to get accurate seq_len.
    from transformers import AutoTokenizer

    tokenizer = AutoTokenizer.from_pretrained(base_id, trust_remote_code=True)
    prompts = [_build_prompt(seq_len, tokenizer, i) for i in range(n_prompts)]
    del tokenizer

    print(f"[uc bench] base model:  {base_id}")
    print(f"[uc bench] packed dir:  {packed_dir}")
    print(f"[uc bench] device:      {device}  ({cuda_name})")
    print(f"[uc bench] n_prompts={n_prompts}  seq_len={seq_len}  n_new={n_new_tokens}")

    # ---- Packed model run ----
    print("[uc bench] loading packed model ...", flush=True)
    try:
        model, tokenizer = _load_packed_model(packed_dir, base_id, device)
        print("[uc bench] running packed model generation ...", flush=True)
        packed_metrics = _run_generation(model, tokenizer, prompts, n_new_tokens, device)
        del model, tokenizer
        _free_memory()
    except torch.cuda.OutOfMemoryError as exc:
        warnings_list.append(f"packed_oom: {exc}")
        _free_memory()
        packed_metrics = {
            "ttft_s_mean": float("nan"),
            "tps_overall": float("nan"),
            "tps_decode_only": float("nan"),
            "peak_vram_gb": float("nan"),
        }

    result = BenchResult(
        model_id=base_id,
        n_prompts=n_prompts,
        seq_len=seq_len,
        n_new_tokens=n_new_tokens,
        device=device,
        cuda_device_name=cuda_name,
        ttft_s_mean=round(packed_metrics["ttft_s_mean"], 4),
        tps_overall=round(packed_metrics["tps_overall"], 2),
        tps_decode_only=round(packed_metrics["tps_decode_only"], 2),
        peak_vram_gb=round(packed_metrics["peak_vram_gb"], 3),
        timestamp=timestamp,
        warnings=warnings_list,
    )

    # ---- Optional baseline run ----
    if baseline:
        print("[uc bench] loading bf16 baseline ...", flush=True)
        try:
            from transformers import AutoModelForCausalLM, AutoTokenizer

            tokenizer = AutoTokenizer.from_pretrained(base_id, trust_remote_code=True)
            baseline_model = AutoModelForCausalLM.from_pretrained(
                base_id, torch_dtype=torch.bfloat16,
                device_map=torch.device(device), trust_remote_code=True,
            ).train(False)
            print("[uc bench] running baseline generation ...", flush=True)
            baseline_metrics = _run_generation(
                baseline_model, tokenizer, prompts, n_new_tokens, device
            )
            del baseline_model, tokenizer
            _free_memory()

            result.baseline_ttft_s_mean = round(baseline_metrics["ttft_s_mean"], 4)
            result.baseline_tps_overall = round(baseline_metrics["tps_overall"], 2)
            result.baseline_tps_decode_only = round(baseline_metrics["tps_decode_only"], 2)
            result.baseline_peak_vram_gb = round(baseline_metrics["peak_vram_gb"], 3)
            if baseline_metrics["tps_overall"] > 0:
                result.comparison = {
                    "tps_pct_change": round(
                        100.0 * (result.tps_overall - result.baseline_tps_overall)
                        / result.baseline_tps_overall, 2,
                    ),
                    "vram_pct_change": round(
                        100.0 * (result.peak_vram_gb - result.baseline_peak_vram_gb)
                        / max(result.baseline_peak_vram_gb, 1e-6), 2,
                    ),
                }
        except torch.cuda.OutOfMemoryError as exc:
            warnings_list.append(f"baseline_oom: {exc}")
            _free_memory()

    # ---- Write JSON + pretty print ----
    out_json.write_text(json.dumps(asdict(result), indent=2), encoding="utf-8")
    print()
    print("=" * 64)
    print(f"  model:               {result.model_id}")
    print(f"  TTFT (s, mean):      {result.ttft_s_mean:.4f}")
    print(f"  TPS overall:         {result.tps_overall:.2f}")
    print(f"  TPS decode-only:     {result.tps_decode_only:.2f}")
    print(f"  peak VRAM (GB):      {result.peak_vram_gb:.3f}")
    if baseline and result.baseline_tps_overall is not None:
        print(f"  baseline TPS:        {result.baseline_tps_overall:.2f}")
        print(f"  baseline VRAM (GB):  {result.baseline_peak_vram_gb:.3f}")
        if result.comparison:
            print(f"  TPS delta vs base:   {result.comparison['tps_pct_change']:+.2f}%")
            print(f"  VRAM delta vs base:  {result.comparison['vram_pct_change']:+.2f}%")
    print(f"  json written:        {out_json}")
    print("=" * 64)
    return result


def cmd_bench(args: argparse.Namespace) -> int:
    """`uc bench <packed_dir>` CLI entry point. Returns process exit code."""
    try:
        bench_packed(
            packed_dir=args.packed_dir,
            n_prompts=int(args.n_prompts),
            seq_len=int(args.seq_len),
            n_new_tokens=int(args.n_new_tokens),
            device=str(args.device),
            baseline=bool(args.baseline),
            base_model_hf_id=getattr(args, "base_model", None),
            out_json=getattr(args, "out_json", None),
        )
        return 0
    except (FileNotFoundError, ValueError, ImportError) as exc:
        print(f"[FAILED] {type(exc).__name__}: {exc}")
        return 2


__all__ = ["bench_packed", "cmd_bench", "BenchResult"]
