"""
LIVING FRR — The model adapts during inference. Not frozen. ALIVE.

Standard FRR: shared block + FIXED modulation per layer.
Living FRR: shared block + ADAPTIVE modulation that changes based on input.

The modulation IS the intelligence — it steers the shared block.
If modulation adapts in real-time, the model is a LIVING PROCESS.

How it works:
1. Shared block (frozen after training) = the engine
2. A tiny "adaptation network" (1-2 layers, ~10K params) reads the
   current hidden state and GENERATES the modulation for the next pass
3. Different inputs → different modulation paths → different behavior
4. The adaptation network IS the "brain" — it decides how to think

This is Sip's "process not model":
- The shared block is the hardware (CPU)
- The adaptation network is the operating system
- The input determines the program
- Intelligence emerges from the PROCESS of adapting, not from static weights

Test-time adaptation: the model can keep learning DURING inference
by updating only the adaptation network (10K params, trivially fast).

Nobody has: FRR + adaptive modulation + test-time learning.
"""
import torch
import torch.nn as nn
import torch.nn.functional as F
import math


class AdaptiveModulator(nn.Module):
    """Tiny network that generates modulation from the current state.

    Takes: current hidden state (B, S, D)
    Outputs: gamma (B, 1, D), beta (B, 1, D) for the next pass

    ~10K params total. This IS the adaptive intelligence.
    """
    def __init__(self, hidden_dim, bottleneck=32):
        super().__init__()
        # Compress hidden state → tiny bottleneck → expand to modulation
        self.compress = nn.Linear(hidden_dim, bottleneck, bias=False)
        self.expand_gamma = nn.Linear(bottleneck, hidden_dim, bias=False)
        self.expand_beta = nn.Linear(bottleneck, hidden_dim, bias=False)

        # Initialize to identity (gamma=1, beta=0)
        nn.init.zeros_(self.expand_gamma.weight)
        nn.init.zeros_(self.expand_beta.weight)

    def forward(self, x):
        """x: (B, S, D) → gamma: (B, 1, D), beta: (B, 1, D)"""
        # Pool across sequence to get a single representation
        h = x.mean(dim=1)  # (B, D)
        h = F.silu(self.compress(h))  # (B, bottleneck)
        gamma = 1.0 + self.expand_gamma(h).unsqueeze(1)  # (B, 1, D), centered at 1
        beta = self.expand_beta(h).unsqueeze(1)  # (B, 1, D), centered at 0
        return gamma, beta


class LivingFRR(nn.Module):
    """FRR where modulation adapts to the input in real-time.

    The shared block is applied 28 times, but each time the modulation
    is GENERATED by the adaptive modulator based on the current state.
    Different inputs take different paths through the same block.

    Optional: test-time training updates the modulator during inference.
    """
    def __init__(self, hidden_dim, n_heads, n_scales, iters_per_scale, vocab_size,
                 modulator_bottleneck=32,
                 embed_weight=None, lm_head_weight=None, norm_weight=None):
        super().__init__()
        self.n_scales = n_scales
        self.iters_per_scale = iters_per_scale
        self.total_layers = n_scales * iters_per_scale
        self.n_heads = n_heads
        self.head_dim = hidden_dim // n_heads

        # THE SHARED BLOCK (same as standard FRR)
        self.qkv = nn.Linear(hidden_dim, 3 * hidden_dim, bias=False)
        self.o_proj = nn.Linear(hidden_dim, hidden_dim, bias=False)
        self.ffn_gate = nn.Linear(hidden_dim, hidden_dim * 3, bias=False)
        self.ffn_up = nn.Linear(hidden_dim, hidden_dim * 3, bias=False)
        self.ffn_down = nn.Linear(hidden_dim * 3, hidden_dim, bias=False)
        self.norm1 = nn.RMSNorm(hidden_dim)
        self.norm2 = nn.RMSNorm(hidden_dim)

        # THE ADAPTIVE MODULATOR (the "living" part)
        self.modulator = AdaptiveModulator(hidden_dim, modulator_bottleneck)

        # Iteration scaling (still per-layer, but could also be adaptive)
        self.iter_scale = nn.ParameterList([
            nn.Parameter(torch.ones(1)) for _ in range(self.total_layers)
        ])

        # Embeddings
        if embed_weight is not None:
            self.embed = nn.Embedding.from_pretrained(embed_weight, freeze=True)
        else:
            self.embed = nn.Embedding(vocab_size, hidden_dim)
        self.out_norm = nn.RMSNorm(hidden_dim)
        if norm_weight is not None:
            self.out_norm.weight = nn.Parameter(norm_weight, requires_grad=False)
        self.lm_head = nn.Linear(hidden_dim, vocab_size, bias=False)
        if lm_head_weight is not None:
            self.lm_head.weight = nn.Parameter(lm_head_weight, requires_grad=False)

    def forward(self, tokens):
        x = self.embed(tokens).float()
        B, S, D = x.shape

        layer_count = 0
        for scale in range(self.n_scales):
            for it in range(self.iters_per_scale):
                # ADAPTIVE: generate modulation from current state
                gamma, beta = self.modulator(x)

                # Apply shared block with adaptive modulation
                h = self.norm1(x) * gamma + beta
                qkv = self.qkv(h).reshape(B, S, 3, self.n_heads, self.head_dim).permute(2, 0, 3, 1, 4)
                q, k, v = qkv[0], qkv[1], qkv[2]
                attn = (q @ k.transpose(-2, -1)) / math.sqrt(self.head_dim)
                if S > 1:
                    mask = torch.triu(torch.ones(S, S, device=x.device), diagonal=1).bool()
                    attn = attn.masked_fill(mask, float('-inf'))
                attn = F.softmax(attn, dim=-1)
                out = (attn @ v).transpose(1, 2).reshape(B, S, D)
                x_attn = x + self.o_proj(out)

                h = self.norm2(x_attn) * gamma + beta
                gate = F.silu(self.ffn_gate(h))
                x_new = x_attn + self.ffn_down(gate * self.ffn_up(h))

                x = x + (x_new - x) * torch.sigmoid(self.iter_scale[layer_count])
                layer_count += 1

        x = self.out_norm(x)
        return self.lm_head(x)
