"""
WEIGHT PROGRAM — Intelligence as executable code, not stored weights.

Instead of storing 7M params, store a PROGRAM that generates them.
The program is tiny (kilobytes). When you need weights, run the program.

This is the process vision: the program IS the intelligence.
It doesn't STORE what a transformer knows — it COMPUTES it on demand.

For existing models: reverse-engineer the program that generates their weights
For new models: evolve/train the program directly

The program uses simple operations:
- Generate weight matrix at (layer, row, col) position
- Use position-dependent formulas (like positional encoding but for weights)
- Tiny: the program might be 1000 lines of "code" (params)
  that generate millions of weights on the fly

This is related to:
- Neural Radiance Fields (NeRF): tiny MLP generates entire 3D scene
- Implicit Neural Representations: coordinates → values
- Hypernetworks: one network generates another's weights

But OURS is different because it's RECURSIVE — the same program
generates ALL layers through position-dependent evaluation.
"""
import torch
import torch.nn as nn
import torch.nn.functional as F
import math


class WeightProgram(nn.Module):
    """A tiny program that generates weight matrices on the fly.

    Input: (layer_id, position_in_matrix) — where in the model
    Output: weight value at that position

    The program is a tiny MLP with ~10K params that generates
    ALL weights for ALL layers when queried with coordinates.
    """
    def __init__(self, program_dim=64, n_program_layers=3):
        super().__init__()
        # The program itself — tiny MLP
        layers = []
        layers.append(nn.Linear(4, program_dim))  # input: (layer_frac, row_frac, col_frac, matrix_type)
        layers.append(nn.GELU())
        for _ in range(n_program_layers - 2):
            layers.append(nn.Linear(program_dim, program_dim))
            layers.append(nn.GELU())
        layers.append(nn.Linear(program_dim, 1))  # output: weight value
        self.program = nn.Sequential(*layers)

        # Fourier features for better coordinate encoding
        self.n_freq = 8
        # Total input: 4 coords * (2 * n_freq + 1) = 4 * 17 = 68
        self.program[0] = nn.Linear(4 * (2 * self.n_freq + 1), program_dim)

    def encode_coords(self, coords):
        """Fourier feature encoding for coordinates."""
        # coords: (..., 4)
        encoded = [coords]
        for freq in range(self.n_freq):
            encoded.append(torch.sin(2 ** freq * math.pi * coords))
            encoded.append(torch.cos(2 ** freq * math.pi * coords))
        return torch.cat(encoded, dim=-1)

    def generate_weight(self, layer_frac, row_frac, col_frac, matrix_type):
        """Generate a single weight value.

        layer_frac: 0-1, which layer (0=first, 1=last)
        row_frac: 0-1, row position
        col_frac: 0-1, column position
        matrix_type: 0-1, which matrix (0=Q, 0.2=K, 0.4=V, 0.6=gate, 0.8=up, 1.0=down)
        """
        coords = torch.stack([layer_frac, row_frac, col_frac, matrix_type], dim=-1)
        encoded = self.encode_coords(coords)
        return self.program(encoded).squeeze(-1)

    def generate_matrix(self, layer_frac, matrix_type, rows, cols, device='cuda'):
        """Generate an entire weight matrix for a given layer and matrix type."""
        row_fracs = torch.linspace(0, 1, rows, device=device)
        col_fracs = torch.linspace(0, 1, cols, device=device)
        grid_r, grid_c = torch.meshgrid(row_fracs, col_fracs, indexing='ij')

        layer_grid = torch.full_like(grid_r, layer_frac)
        type_grid = torch.full_like(grid_r, matrix_type)

        coords = torch.stack([layer_grid, grid_r, grid_c, type_grid], dim=-1)
        encoded = self.encode_coords(coords)
        weights = self.program(encoded).squeeze(-1)
        return weights


class ProgrammedTransformer(nn.Module):
    """A transformer where ALL weights are generated by a tiny program.

    Instead of storing 7M params, stores a ~10K param program.
    At inference: program generates weights → weights used for computation.

    The program IS the model. The weights are ephemeral.
    """
    def __init__(self, hidden_dim, n_heads, n_layers=28,
                 program_dim=64, vocab_size=151936,
                 embed_weight=None, lm_head_weight=None, norm_weight=None):
        super().__init__()
        self.hidden_dim = hidden_dim
        self.n_heads = n_heads
        self.n_layers = n_layers
        self.head_dim = hidden_dim // n_heads

        # THE PROGRAM — generates ALL weights
        self.program = WeightProgram(program_dim=program_dim)

        # Per-layer norms (tiny, keep explicit)
        self.norms = nn.ModuleList([nn.RMSNorm(hidden_dim) for _ in range(n_layers * 2)])

        # Embedding and head (shared)
        if embed_weight is not None:
            self.embed = nn.Embedding.from_pretrained(embed_weight, freeze=True)
        else:
            self.embed = nn.Embedding(vocab_size, hidden_dim)
        self.lm_head = nn.Linear(hidden_dim, vocab_size, bias=False)
        if lm_head_weight is not None:
            self.lm_head.weight = nn.Parameter(lm_head_weight, requires_grad=False)
        self.out_norm = nn.RMSNorm(hidden_dim)
        if norm_weight is not None:
            self.out_norm.weight = nn.Parameter(norm_weight, requires_grad=False)

    def forward(self, tokens):
        B, T = tokens.shape
        x = self.embed(tokens).float()
        device = x.device

        for layer in range(self.n_layers):
            layer_frac = layer / max(1, self.n_layers - 1)

            # Generate QKV weights on the fly
            qkv_w = self.program.generate_matrix(
                layer_frac, 0.0, 3 * self.hidden_dim, self.hidden_dim, device)

            # Attention
            h = self.norms[layer * 2](x)
            qkv = F.linear(h, qkv_w)
            qkv = qkv.reshape(B, T, 3, self.n_heads, self.head_dim)
            qkv = qkv.permute(2, 0, 3, 1, 4)
            q, k, v = qkv[0], qkv[1], qkv[2]

            attn = (q @ k.transpose(-2, -1)) / math.sqrt(self.head_dim)
            if T > 1:
                mask = torch.triu(torch.ones(T, T, device=device), diagonal=1).bool()
                attn = attn.masked_fill(mask, float('-inf'))
            attn = F.softmax(attn, dim=-1)
            out = (attn @ v).transpose(1, 2).reshape(B, T, self.hidden_dim)

            # Generate output projection on the fly
            o_w = self.program.generate_matrix(
                layer_frac, 0.2, self.hidden_dim, self.hidden_dim, device)
            x = x + F.linear(out, o_w)

            # Generate FFN weights on the fly
            gate_w = self.program.generate_matrix(
                layer_frac, 0.5, self.hidden_dim, self.hidden_dim, device)
            up_w = self.program.generate_matrix(
                layer_frac, 0.7, self.hidden_dim, self.hidden_dim, device)
            down_w = self.program.generate_matrix(
                layer_frac, 0.9, self.hidden_dim, self.hidden_dim, device)

            h = self.norms[layer * 2 + 1](x)
            x = x + F.linear(F.silu(F.linear(h, gate_w)) * F.linear(h, up_w), down_w)

        x = self.out_norm(x)
        return self.lm_head(x)

    def program_size(self):
        return sum(p.numel() for p in self.program.parameters())
